"""Differential operand-tokenizer test against the 312042e behavior.
Runs 20,000 generated inputs plus delimiter/literal/length boundary cases.
Requires a host C compiler with address and undefined-behavior sanitizers.
"""
from pathlib import Path
import subprocess, tempfile, os
root=Path(__file__).resolve().parents[2]
s=root.joinpath('src/utils.c').read_text()
a=s.index('uint8_t getOperandToken('); b=s.index('// Returns a bracketed token', a)
current=s[a:b]
reference="uint8_t referenceToken(streamtoken_t *token, char *src) {\n    uint8_t length = 0;\n    bool inliteral = false;\n\n    // skip leading space\n    while(ISSPACE(*src)) src++;\n    if(*src == 0) {\n        memset(token, 0, sizeof(streamtoken_t));\n        return 0;\n    }\n    token->start = src;\n\n    // hunt for end-character (0 , or ; in normal non-literal mode)\n    //\n    // Only three characters can matter, so ordinary ones get past on three\n    // comparisons with no state to load; the literal flag is only consulted\n    // once one of the three turns up.\n    while(*src) {\n        if((*src == ',') || (*src == ';') || (*src == '\\'')) {\n            if(*src == '\\'') {\n                if(inliteral) {\n                    if(*(src+1) == '\\'') {\n                        src++;\n                        length++;\n                    }\n                    inliteral = false;\n                }\n                else inliteral = true;\n            }\n            else if(!inliteral) break;\n        }\n        src++;\n        length++;\n    }\n\n    token->terminator = *src;\n    if(*src) token->next = src+1;\n    else token->next = src;\n\n    if(length) {\n        *src-- = 0; // terminate early and revert one character\n        while(ISSPACE(*src)) { // remove trailing space(s)\n            *src-- = 0; // terminate on trailing spaces\n            if(length-- == 0) break;\n        }\n    }\n    return length;\n}\n\n"
harness='\nstatic unsigned seed=12345;\nstatic unsigned rnd(void) { seed=seed*1664525u+1013904223u; return seed; }\nstatic void check(const char *input) {\n char a[600],b[600]; streamtoken_t x,y;\n strcpy(a,input);strcpy(b,input);\n unsigned na=referenceToken(&x,a),nb=getOperandToken(&y,b);\n if(na!=nb || x.terminator!=y.terminator ||\n    (x.start?x.start-a:-1)!=(y.start?y.start-b:-1) ||\n    (x.next?x.next-a:-1)!=(y.next?y.next-b:-1) ||\n    (na && strcmp(x.start,y.start))) {\n   fprintf(stderr,"Tokenizer mismatch on input: %s\\n",input);exit(1);\n }\n}\nint main(void) {\n const char *cases[]={"", " ", ",x", ";comment", "a, b", "af\'", "\'a,b;c\' ;tail", "\'a\'\'b\',x", "( ix + target )  ;comment", "\'unterminated ; x", "a\\t\\t, b", "\' \'\\t; x"};\n unsigned i,j;\n for(i=0;i<sizeof(cases)/sizeof(cases[0]);i++)check(cases[i]);\n for(i=0;i<20000;i++) {\n   char input[260];unsigned n=rnd()%250;\n   for(j=0;j<n;j++) { static const char chars[]="abc012()[]+-*/ ,;\'\\t\\r\\n\\v\\f";input[j]=chars[(rnd()>>16)%(sizeof(chars)-1)]; }\n   input[n]=0;check(input);\n }\n for(i=254;i<=256;i++) { char input[260];memset(input,\'a\',i);input[i]=\',\';input[i+1]=0;check(input); }\n puts("20,000 generated token cases and 15 explicit/boundary cases passed");\n}\n'
with tempfile.TemporaryDirectory(prefix='tokens-',dir='/tmp') as folder:
 p=Path(folder)
 (p/'test.c').write_text('#include <stdint.h>\n#include <stdbool.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include "ctype_tab.h"\ntypedef struct { char *start, *next; char terminator; } streamtoken_t;\n'+reference+current+harness)
 subprocess.run(['cc','-O1','-g','-fsanitize=address,undefined','-I'+str(root/'src'),str(p/'test.c'),str(root/'src/ctype_tab.c'),'-o',str(p/'test')],check=True)
 subprocess.run([str(p/'test')],env=dict(os.environ,ASAN_OPTIONS='detect_leaks=0'),check=True)
